export {default as HomeLayout} from './HomeLayout'
export {default as Login} from './Login'
export {default as Register} from './Register'
export {default as ErrorPage} from './Errorpage'
export {default as About} from './About'
export {default as Landing} from './Landing'